sudo: required
services:
  - docker

before_install:
  - docker build markapayne/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true markapayne/react-test npm test

after_success:
  - docker build -t markapayne/multi-client ./client
  - docker build -t markapayne/multi-nginx ./nginx
  - docker build -t markapayne/multi-server ./server
  - docker build -t markapayne/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker
  - docker push markapayne/multi-client
  - docker push markapayne/multi-nginx
  - docker push markapayne/multi-server
  - docker push markapayne/multi-worker